# Generated by Django 5.1.6 on 2025-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='size',
            field=models.CharField(blank=True, default='M', max_length=10, null=True),
        ),
    ]
